export const CODIGOS_ERRO = {
  NOME_INVALIDO: "VAL-001",
  IDADE_INVALIDA: "VAL-002",
  CPF_INVALIDO: "VAL-003",
  TELEFONE_INVALIDO: "VAL-004",
  SINTOMAS_INVALIDOS: "VAL-005",

  PACIENTE_NAO_ENCONTRADO: "PAC-001",
  CPF_JA_CADASTRADO: "PAC-002",

  PRIORIDADE_INVALIDA: "TRI-001",

  ERRO_INTERNO: "SYS-001",
  FALHA_CARREGAMENTO_API: "API-001",
} as const;

export type CodigoErro =
  (typeof CODIGOS_ERRO)[keyof typeof CODIGOS_ERRO];